baseURL = ""
languageCode = "en-us"
title = "Mila Frerichs"
enableEmoji = true

[menu]

  [[menu.main]]
    identifier = "civicvision"
    name = "Company"
    url = "https://civicvision.de"
    weight = 110
