baseURL = ""
languageCode = "en-us"
title = "Mila Frerichs, Data Visualization consultant for social good"
enableEmoji = true
cloudinary_url = "https://res.cloudinary.com/civicvision/image/upload"
keywords = ["Data Visualization", "Consultant", "Data Storytelling", "Geospatial", "Maps", "visualization for social good", "non-profit", "civic advocacy"]

[taxonomies]
featured = "featured"
category = "categories"

[params]
  description = "Mila Frerichs is a Data Visualization Consultant who helps civic advocacy groups improve the life of citizens with the help of Open Data. He uses the power of public open data and open source to build tools and (geospatial) data visualizations to increase transparency and accountability. He uses his software development skills for social good. "

